Use JSON API and capture new bike_list data
AquaQAnalytics/TorQ-Bikes pull request #3
Opened 2020-03-10 11:24 UTC by jlogan540

## A rough outline of the improvements are:
- Update API URL to grab data as JSON as this can be handled easily with .j.k. Removed xml specific code as a result.
- Add basic tests of the JSON parsing functionality.
- replaced wget with curl and have the output directed to stdout instead of using the file bikes.xml to store it.
- params seemed to be identical to .proc.params so I updated all references to it.
- webpage flag seems unnecessary as the API URL will probably only change infrequently, moved this into config instead.
- Use inbuilt TorQ logging for fullbikedataprotected instead of show.
- Capture new bike_list data coming from the API.
## May also address:
- [x]  Add namespace for bikes code.
- [ ] Having date passed to writedown function and removing all dates <.z.D-1 instead of =.z.D-2.
- [x] Using .Q.hg instead of curl.
- [ ] Move code/belfastbikes/bikes.q to code/processes/belfastbikes.q.
- [ ]  Update README.md to include minimum working version of kdb.
- [ ] Creating a release tag after merge.

2020-03-10 11:29 UTC, ThomasSmyth commented on code/belfastbikes/bikes.q
> +  //bike_tab:@[bike_tab;`name`state;`$];
Remove this comment.

2020-03-10 11:55 UTC, tsmyth-aquaq approved these changes

2020-03-10 11:56 UTC, jemmaborland approved these changes
Actual code looks good to me, just minor tweaks in readme

2020-03-10 11:56 UTC, jemmaborland commented on README.md
> +The process will run for 14 day once it starts, collecting data every 30 seconds.
```suggestion
The process will run for 14 days once it starts, collecting data every 30 seconds.
```

2020-03-10 11:56 UTC, jemmaborland commented on README.md
> +number variable in `deploy/setenv.sh`, the default value is 238 (Belfast).
```suggestion
number variable in `deploy/setenv.sh`; the default value is 238 (Belfast).
```

2020-03-10 11:56 UTC, jemmaborland commented on README.md
> +usage, we can create a mapping of 'routes' that each bike has taken, I.e. where
```suggestion
usage, we can create a mapping of 'routes' that each bike has taken, i.e. where
```

2020-03-10 11:56 UTC, jemmaborland commented on README.md
> +This reads the data to the in memory table `place`. Which can then be written to
```suggestion
This reads the data to the in-memory table `place`, which can then be written to
```

2020-03-10 11:56 UTC, jemmaborland commented on README.md
> +To query the persisted data in the hdb, we can either load in a specific date
```suggestion
To query the persisted data in the HDB, we can either load in a specific date
```

2020-03-10 11:56 UTC, jemmaborland commented on README.md
> +a range of dates. To load in the hdb to a q session we can run the following command:
```suggestion
a range of dates. To load in the HDB to a q session we can run the following command:
```

2020-03-17 15:35 UTC, picoDoc requested changes
great work 👍  Tested it out and all seems to work for me.  Two additions/issues that I found:
* can you add a stop script that cleanly shuts it down, saving data to disk?
* I noticed that the writedown will overwrite whatever is currently in the hdb for that date, so for example if you shutdown midday, and started back up, the next save down would overwrite the data before the shutdown.  Can you fix this?

2020-03-19 10:37 UTC, jemmaborland commented on README.md
> -
Can you add a bit in here about the usage of stop_bikes.sh?

2020-03-19 10:37 UTC, jemmaborland commented on code/util/intradaybikeswd.q
> +conn:.Q.def[(enlist `conn)!enlist 1;.Q.opt .z.x][`conn]
is 1 a sensible default here? would it worthwhile making it a null, then error trapping below if the port isn't open/null/can't be connected to for whatever reason?

2020-03-19 15:28 UTC, picoDoc approved these changes

2020-03-19 16:45 UTC, jemmaborland approved these changes

2020-03-19 17:49 UTC, merged